export const PLANS = {
  free: {
    id: "free",
    name: "Free",
    price: 0,
    currency: "INR",
    questionsPerDay: 1,
    badge: null,
    search: "basic",
    bookmarks: "standard",
    profileVisibility: "standard",
    prioritySupport: false,
    goldCommunity: false,
    razorpayPlanId: null,
  },
  bronze: {
    id: "bronze",
    name: "Bronze",
    price: 99,
    currency: "INR",
    questionsPerDay: 5,
    badge: "bronze",
    search: "advanced",
    bookmarks: "standard",
    profileVisibility: "standard",
    prioritySupport: false,
    goldCommunity: false,
    razorpayPlanId: process.env.RAZORPAY_PLAN_BRONZE || null,
  },
  silver: {
    id: "silver",
    name: "Silver",
    price: 299,
    currency: "INR",
    questionsPerDay: 15,
    badge: "silver",
    search: "advanced",
    bookmarks: "unlimited",
    profileVisibility: "enhanced",
    prioritySupport: true,
    goldCommunity: false,
    razorpayPlanId: process.env.RAZORPAY_PLAN_SILVER || null,
  },
  gold: {
    id: "gold",
    name: "Gold",
    price: 999,
    currency: "INR",
    questionsPerDay: -1,
    badge: "gold",
    search: "priority",
    bookmarks: "unlimited",
    profileVisibility: "featured",
    prioritySupport: true,
    goldCommunity: true,
    razorpayPlanId: process.env.RAZORPAY_PLAN_GOLD || null,
  },
};

export const PAID_PLANS = ["bronze", "silver", "gold"];

export const getPlanConfig = (planId) => PLANS[planId] || PLANS.free;
